<?
header("Content-type:application/pdf");
header("Cache-Control: no-cache");
header("Pragma: no-cache");
require('/usr/share/php/fpdf/fpdf.php');
include_once('../../../common.inc.php'); 
include_once('../../../../classes/function.numeros.php'); 

$pdf=new FPDF('P','mm', array(279, 367));
$pdf->SetAutoPageBreak(false, 10);
$pdf->AddPage();
//$pdf->SetFont('Roman','',12);
$pdf->SetFont('Arial','',12);
//$pdf->SetTextColor(20,20,20);
//$pdf->SetTextColor(50,50,50);
$pdf->SetTopMargin(0);
//$pdf->SetLeftMargin(-20);


$data = new inscripcionTable();
$data->readEnv();

if ($data->request['idinscripcion']) {
	$rows = $data->readDataSQL("SELECT n.*, hv.*, ins.*, ac.idtomo, ac.folio, ac.partida, ac.fecha, t.numero FROM nacimiento n INNER JOIN hechovital hv ON n.idnacimiento=hv.idhechovital INNER JOIN inscripcion ins ON hv.idhechovital= ins.idinscripcion LEFT JOIN acta ac ON ac.idinscripcion= ins.idinscripcion INNER JOIN tomo t on t.idtomo=ac.idtomo WHERE ac.idinscripcion='" . $data->request['idinscripcion'] ."'");
        $row = $rows[0];
	//print_r($row);
     	//$pdf->Image('./imgs/acta_nacimiento_frente.jpg', 44,23, 222.50,328.17 );
	$pdf->SetY(41);
	$pdf->SetX(142);
	$pdf->Cell(0,0,strtoupper('Matagalpa'));
	$pdf->SetY(32);
	$pdf->SetX(235);
	$pdf->Cell(0,0,$row['numero']);
	$pdf->SetY(40);
	$pdf->SetX(235);
	$pdf->Cell(0,0,$row['folio']);
	$pdf->SetY(44);
	$pdf->SetX(240);
	$pdf->Cell(0,0,$row['partida']);
	$pdf->SetY(50);
	$pdf->SetX(235);
	$fecha_acta= new Datetime($row['fecha']);
	$pdf->Cell(0,0,$fecha_acta->format('d/m/Y'));
	$pdf->SetY(60);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['inscrito1nombre1']));
	$pdf->Sety(60);
	$pdf->SetX(105);
	$pdf->Cell(0,0,strtoupper($row['inscrito1nombre2']));
	$pdf->SetY(60);
	$pdf->SetX(160);
	$pdf->Cell(0,0,strtoupper($row['inscrito1apellido1']));
	$pdf->Sety(60);
	$pdf->SetX(215);
	$pdf->Cell(0,0,strtoupper($row['inscrito1apellido2']));
	$pdf->Sety(70);
	$pdf->SetX(55);
	$pdf->Cell(0,0,strtoupper($row['ciudadinscripcion']));
	$pdf->Sety(70);
	$pdf->SetX(180);
	$pdf->Cell(0,0,strtoupper($row['municipioinscripcion']));
	$pdf->Sety(77);
	$pdf->SetX(85);
	$pdf->Cell(0,0,strtoupper($row['departamentoinscripcion']));
	$pdf->Sety(77);
	$pdf->SetX(137);
	$fecha_inscripcion= new DateTime($row['fecha']);
	$fecha_inscripcion_parts= getdate($fecha_inscripcion->getTimestamp());
	$prt_fecha_inscripcion=number2str($fecha_inscripcion->format('g'));
	$prt_fecha_inscripcion.=" CON ". number2str($fecha_inscripcion_parts['minutes']);
	$pdf->Cell(0,0,$prt_fecha_inscripcion);
	$pdf->Sety(77);
	$pdf->SetX(230);
	$pdf->Cell(0,0,utf8_decode(($fecha_inscripcion_parts['hours']>12)?'TARDE':'MAÑANA'));
	$pdf->Sety(84);
	$pdf->SetX(65);
	$prt_dia_inscripcion= number2str($fecha_inscripcion_parts['mday']);
	$pdf->Cell(0,0,$prt_dia_inscripcion);
	$pdf->SetY(84);
	$pdf->SetX(130);
	$pdf->Cell(0,0,strtoupper(strftime('%B',$fecha_inscripcion->getTimestamp())));
	$pdf->SetY(84);
	$pdf->SetX(212);
	$pdf->Cell(0,0,number2str($fecha_inscripcion->format('y')));
	$pdf->Sety(100);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nombre']));
	$pdf->SetY(100);
	$pdf->SetX(185);
	$pdf->Cell(0,0,number2str($row['compareciente1edad']));
	$pdf->SetY(113);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['compareciente1oficio']));
	$pdf->SetY(112);
	$pdf->SetX(93);
	$pdf->SetFont('Arial','',8);
	$pdf->MultiCell(70,3.0,strtoupper($row['compareciente1domicilio']));
	//$pdf->Cell(0,0,strtoupper($row['compareciente1domicilio']));
	$pdf->SetFont('Arial','',12);
	$pdf->SetY(113);
	$pdf->SetX(175);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nacionalidad']));
	$pdf->SetY(113);
	$pdf->SetX(225);
	$pdf->Cell(0,0,strtoupper($row['compareciente1cedula']));
	$pdf->SetY(128);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['compareciente2nombre']));
	$pdf->SetY(128);
	$pdf->SetX(185);
	$pdf->Cell(0,0,number2str($row['compareciente2edad']));
	$pdf->SetY(142);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['compareciente2oficio']));
	$pdf->SetY(141);
	$pdf->SetX(93);
	$pdf->SetFont('Arial','',8);
	$pdf->MultiCell(70,3.0,strtoupper($row['compareciente1domicilio']));
	$pdf->SetFont('Arial','',12);
	//$pdf->Cell(0,0,'Domicilio');
	$pdf->SetY(142);
	$pdf->SetX(175);
	$pdf->Cell(0,0,strtoupper($row['compareciente2nacionalidad']));
	$pdf->SetY(142);
	$pdf->SetX(225);
	$pdf->Cell(0,0,strtoupper($row['compareciente2cedula']));
	$pdf->SetY(157);
	$pdf->SetX(85);
	$fecha_nacimiento= new DateTime($row['fechanacimiento']);
	$fecha_nacimiento_parts= getdate($fecha_nacimiento->getTimestamp());
	$prt_hora_nacimiento=number2str($fecha_nacimiento->format('g'));
	$prt_hora_nacimiento.=" CON ". number2str($fecha_nacimiento_parts['minutes']);
	$pdf->Cell(0,0,$prt_hora_nacimiento);
	$pdf->SetY(157);
	$pdf->SetX(207);
	$pdf->Cell(0,0,utf8_decode(($fecha_nacimiento_parts['hours']>12)?'TARDE':'MAÑANA'));
	$pdf->SetY(165);
	$pdf->SetX(63);
	$prt_dia_nacimiento= number2str($fecha_nacimiento_parts['mday']);
	$pdf->Cell(0,0,$prt_dia_nacimiento);
	$pdf->SetY(165);
	$pdf->SetX(130);
	$pdf->Cell(0,0,strtoupper(strftime('%B',$fecha_nacimiento->getTimestamp())));
	$pdf->SetY(165);
	$pdf->SetX(220);
	$pdf->Cell(0,0,number2str($fecha_nacimiento->format('y')));
	$pdf->SetY(183);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['ciudadnacimiento']));
	$pdf->SetY(183);
	$pdf->SetX(108);
	$pdf->Cell(0,0,strtoupper($row['municipionacimiento']));
	$pdf->SetY(183);
	$pdf->SetX(173);
	$pdf->Cell(0,0,strtoupper($row['departamentonacimiento']));
	$pdf->SetY(183);
	$pdf->SetX(220);
	$pdf->Cell(0,0,strtoupper($row['paisnacimiento']));
	$pdf->SetY(197);
	$pdf->SetX(63);
	$nac_full_name= array($row['inscrito1nombre1'],$row['inscrito1nombre2'], $row['inscrito1apellido1'], $row['inscrito1apellido2']) ;
	$pdf->Cell(0,0,strtoupper(implode(" ",$nac_full_name)));
	$pdf->SetY(197);
	$pdf->SetX(244);
	$sexo= $row['sexoinscrito'];
	$pdf->Cell(0,0,($sexo=="m")?"X":"");
	$pdf->SetY(197);
	$pdf->SetX(261);
	$pdf->Cell(0,0,($sexo=="f")?"X":"");
	$pdf->SetY(211);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['padrenombre']));
	$pdf->SetY(211);
	$pdf->SetX(183);
	$pdf->Cell(0,0,number2str($row['edadpadre']));
	$pdf->SetY(228);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['oficiopadre']));
	$pdf->SetY(228);
	$pdf->SetX(95);
	$pdf->Cell(0,0,strtoupper($row['domiciliopadre']));
	$pdf->SetY(228);
	$pdf->SetX(173);
	$pdf->Cell(0,0,strtoupper($row['nacionalidadpadre']));
	$pdf->SetY(228);
	$pdf->SetX(225);
	$pdf->Cell(0,0,strtoupper($row['cedulapadre']));
	$pdf->SetY(240);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['nombremadre']));
	$pdf->SetY(240);
	$pdf->SetX(175);
	$pdf->Cell(0,0,number2str($row['edadmadre']));
	$pdf->SetY(254);
	$pdf->SetX(50);
	$pdf->Cell(0,0,strtoupper($row['oficiomadre']));
	$pdf->SetY(254);
	$pdf->SetX(95);
	$pdf->Cell(0,0,strtoupper($row['domiciliomadre']));
	$pdf->SetY(254);
	$pdf->SetX(173);
	$pdf->Cell(0,0,strtoupper($row['nacionalidadpadre']));
	$pdf->SetY(254);
	$pdf->SetX(224);
	$pdf->Cell(0,0,strtoupper($row['cedulamadre']));
	$pdf->SetY(262);
	$pdf->SetX(45);
	//$nac_ext= 'observaciones deben de ser suficientemente largos como para  probar imprimir en varias lineas de este documento den pdf, sera suficiente?';	
	$nac_ext= "                                     ";
	$nac_ext.=substr($row['enextranjero'],0,220);
	$pdf->MultiCell(220,6.0,$nac_ext);
	$pdf->SetY(274);
	$pdf->SetX(45);
	// $adicionales= 'observaciones deben de ser suficientemente largos como para  probar imprimir en varias lineas de este documento den pdf, sera suficiente?';	
	$adicionales= "                              ";
	$adicionales.= $row['datosadicionales'];
	$pdf->MultiCell(220,6.0,$adicionales);
	$pdf->SetY(286);
	$pdf->SetX(45);
	//$observaciones= 'observaciones deben de ser suficientemente largos como para  probar imprimir en varias lineas de este documento den pdf, sera suficiente?';	
	$observaciones=  "                         ";
	$observaciones.= $row['observaciones'];
	//$pdf->MultiCell(228,5.5,$observaciones);
	$pdf->MultiCell(220,6.0,$observaciones);
	$pdf->SetY(328);
	$pdf->SetX(55);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nombre']));
	$pdf->SetY(328);
	$pdf->SetX(190);
	$pdf->Cell(0,0,strtoupper($row['compareciente2nombre']));
	$pdf->SetY(343);
	$pdf->SetX(55);
	$pdf->Cell(0,0,$row['nombreregistrador']);
	$pdf->SetY(343);
	$pdf->SetX(190);
	$pdf->Cell(0,0,$row['nombresecretario']);
	#pagina de atras
	$pdf->AddPage();
	$pdf->SetTopMargin(8);
	$pdf->SetLeftMargin(0);
	//$pdf->Image('./imgs/acta_nacimiento_atras.jpg', 12,31, 222.50,328.17);
	//$pdf->Image('./imgs/acta_nacimiento_atras.jpg', 0,31, 222.50,328.17);
	$pdf->SetY(29);
	//$pdf->SetX(13);
	$pdf->SetX(1);


	$notasmarginales= $data->readDataSQL("SELECT cuerpo FROM notamarginal WHERE idinscripcion=" . $data->request['idinscripcion']." ORDER BY fechamarginacion DESC LIMIT 5");
	$mod_civil="                                                         ";
	if(sizeof($notasmarginales)>0){
		foreach($notasmarginales as $notamarginal){
			$modificaciones[]= $notamarginal['cuerpo'];
		}
		$mod_civil.= utf8_decode(implode(PHP_EOL,$modificaciones));
	}
	//$mod_civil= 'observaciones deben de ser suficientemente largos como para  probar imprimir en varias lineas de este documento den pdf, sera suficiente?';
	$pdf->MultiCell(223,6.8,$mod_civil);
	$def_vc= 356;
	$pdf->SetY($def_vc);
	$pdf->SetX(25);
	$pdf->Cell(0,0,strtoupper($row['lugarinscripciondefuncion']));
	$pdf->SetY($def_vc);
	$pdf->SetX(126);
	$pdf->Cell(0,0,$row['tomoinscripciondefuncion']);
	$pdf->SetY($def_vc);
	$pdf->SetX(155);
	$pdf->Cell(0,0,$row['folioinscripciondefuncion']);
	$pdf->SetY($def_vc);
	$pdf->SetX(189);
	$pdf->Cell(0,0,$row['partidainscripciondefuncion']);
	$pdf->SetY($def_vc);
	$pdf->SetX(207);
	$pdf->Cell(0,0,$row['anyoinscripciondefuncion']);
	
 	
}
$pdf->Output();
?>

