<?
header("Content-type:application/pdf");
header("Cache-Control: no-cache");
header("Pragma: no-cache");
require('/usr/share/php/fpdf/fpdf.php');
include_once('../../../common.inc.php'); 
include_once('../../../../classes/function.numeros.php'); 

$pdf=new FPDF('P','mm', array(255, 352));
$pdf->SetAutoPageBreak(false, 10);
$pdf->AddPage();
$pdf->SetFont('Arial','',12);
$data = new inscripcionTable();
$data->readEnv();

#INSCRIPCIONES DE DEFUNCION
if ($data->request['idinscripcion']) {
	$rows = $data->readDataSQL("SELECT d.*, hv.*, ins.*, ac.folio, ac.partida, ac.fecha, t.numero FROM defuncion d INNER JOIN hechovital hv ON d.iddefuncion=hv.idhechovital INNER JOIN inscripcion ins ON hv.idhechovital= ins.idinscripcion LEFT JOIN acta ac ON ac.idinscripcion= ins.idinscripcion INNER JOIN tomo t ON t.idtomo=ac.idtomo WHERE ac.idinscripcion='" . $data->request['idinscripcion'] ."'");
        $row = $rows[0];
     	$pdf->Image('./imgs/acta-defuncion.png', 24, 15, 226.91,321.56 );
	$pdf->SetY(35);
	$pdf->SetX(100);
	$pdf->Cell(0,0,'MATAGALPA');
	$pdf->SetY(28);
	$pdf->SetX(215);
	$pdf->Cell(0,0,$row['numero']);
	$pdf->SetY(34);
	$pdf->SetX(214);
	$pdf->Cell(0,0,$row['folio']);
	$pdf->SetY(40);
	$pdf->SetX(219);
	$pdf->Cell(0,0,$row['partida']);
	$pdf->SetY(46);
	$pdf->SetX(216);
	$fecha_acta= new Datetime($row['fecha']);
	$pdf->Cell(0,0,$fecha_acta->format('d/m/Y'));
	$pdf->SetY(59);
	$pdf->SetX(26);
	$pdf->Cell(0,0,strtoupper($row['inscrito1nombre1']));
	$pdf->SetX(84);
	$pdf->Cell(0,0,strtoupper($row['inscrito1nombre2']));
	$pdf->SetX(139);
	$pdf->Cell(0,0,strtoupper($row['inscrito1apellido1']));
	$pdf->SetX(198);
	$pdf->Cell(0,0,strtoupper($row['inscrito1apellido1']));
	$pdf->SetY(67);
	$pdf->SetX(30);
	$pdf->Cell(0,0,strtoupper($row['ciudadinscripcion']));
	$pdf->SetX(157);
	$pdf->Cell(0,0,strtoupper($row['municipioinscripcion']));
	$pdf->SetY(74);
	$pdf->SetX(58);
	$pdf->Cell(0,0,strtoupper($row['departamentoinscripcion']));
	$pdf->SetX(117);
	$fecha_inscripcion= new DateTime($row['fecha']);
	$fecha_inscripcion_parts= getdate($fecha_inscripcion->getTimestamp());
	$prt_fecha_inscripcion=number2str($fecha_inscripcion->format('g'));
	$prt_fecha_inscripcion.=" CON ". number2str($fecha_inscripcion_parts['minutes']);
	$pdf->Cell(0,0,$prt_fecha_inscripcion);
	$pdf->SetX(213);
	$pdf->Cell(0,0,utf8_decode(($fecha_inscripcion_parts['hours']>12)?'TARDE':'MAÑANA'));
	$pdf->SetY(81);
	$pdf->SetX(40);
	$prt_dia_inscripcion= number2str($fecha_inscripcion_parts['mday']);
	$pdf->Cell(0,0,$prt_dia_inscripcion);
	$pdf->SetX(110);
	$pdf->Cell(0,0,strtoupper(strftime('%B',$fecha_inscripcion->getTimestamp())));
	$pdf->SetX(220);
	$pdf->Cell(0,0,number2str($fecha_inscripcion->format('y')));
	$pdf->SetY(96);
	$pdf->SetX(25);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nombre']));
	$pdf->SetX(165);
	$pdf->Cell(0,0,number2str($row['compareciente1edad']));
	$pdf->SetY(110);
	$pdf->SetX(25);
	$pdf->Cell(0,0,strtoupper($row['compareciente1oficio']));
	$pdf->SetX(75);
	$pdf->Cell(0,0,'estado_civil');
	$pdf->SetX(122);
	$pdf->SetFont('Arial','',8);
	$pdf->MultiCell(70,3.0,strtoupper($row['compareciente1domicilio']));
	$pdf->SetFont('Arial','',12);
	//$pdf->Cell(0,0,$row['compareciente1domicilio']);
	$pdf->SetX(212);
	$pdf->Cell(0,0,strtoupper($row['compareciente1cedula']));
	$pdf->SetY(122);
	$pdf->SetX(56);
	$fecha_defuncion= new DateTime($row['fechadefuncion']);
	$fecha_defuncion_parts= getdate($fecha_defuncion->getTimestamp());
	$prt_hora_defuncion=number2str($fecha_defuncion->format('g'));
	$prt_hora_defuncion.=" CON ". number2str($fecha_defuncion_parts['minutes']);
	$pdf->Cell(0,0,$prt_hora_defuncion);
	$pdf->SetX(192);
	$pdf->Cell(0,0,utf8_decode(($fecha_defuncion_parts['hours']>12)?'TARDE':'MAÑANA'));
	$pdf->SetY(129);
	$pdf->SetX(40);
	$prt_dia_defuncion= number2str($fecha_defuncion_parts['mday']);
	$pdf->Cell(0,0,$prt_dia_defuncion);
	$pdf->SetX(108);
	$pdf->Cell(0,0,strtoupper(strftime('%B',$fecha_defuncion->getTimestamp())));
	$pdf->SetX(210);
	$pdf->Cell(0,0,number2str($fecha_defuncion->format('y')));
	$pdf->SetY(144);
	$pdf->SetX(26);
	$def_full_name= array($row['inscrito1nombre1'],$row['inscrito1nombre2'], $row['inscrito1apellido1'], $row['inscrito1apellido2']) ;
	$pdf->Cell(0,0,strtoupper(implode(" ",$def_full_name)));
	//$pdf->Cell(0,0,$row['inscrito1nombre1'].' '. $row['inscrito1nombre2'] .' '. $row['inscrito1apellido1'] .' '. $row['inscrito1apellido2']);
	$pdf->SetX(165);
	$pdf->Cell(0,0,number2str($row['edadfallecido' ]));
      	$pdf->SetY(159);
        if ($row['sexoinscrito'] <> 'f') {
  	  $pdf->SetX(43);
	  $pdf->Cell(0,0,'X');
        } else {
	  $pdf->SetX(57);
   	  $pdf->Cell(0,0,'X');

        }
	$pdf->SetX(70);
	$pdf->Cell(0,0,strtoupper($row['oficiofallecido']));
	$pdf->SetX(114);
	$pdf->Cell(0,0,strtoupper($row['estado_civil']));
	$pdf->SetFont('Arial','',8);
      	$pdf->SetY(155);
	$pdf->SetX(165);
	#$pdf->Cell(0,0,$row['domiciliofallecido']);
 	$domiciliofallecido = $row['domiciliofallecido'];
	$pdf->MultiCell(85,2.7,$domiciliofallecido);
	$pdf->SetFont('Arial','',12);
	$pdf->SetY(173);
	$pdf->SetX(27);
	$pdf->Cell(0,0,strtoupper($row['nacionalidadfallecido']));
	$pdf->SetX(68);
	$pdf->Cell(0,0,strtoupper($row['cedulafallecido']));
	$pdf->SetX(110);
	$pdf->Cell(0,0,strtoupper($row['causamuerte']));
	$pdf->SetY(189);
	$pdf->SetX(27);
	$pdf->Cell(0,0,strtoupper($row['conyugenombre']));
	$pdf->SetX(165);
	$pdf->Cell(0,0,'edad_conyuge');
	$pdf->SetY(209);
	$pdf->SetX(28);
	$pdf->Cell(0,0,strtoupper($row['ciudadnacimiento']));
	$pdf->SetX(85);
	$pdf->Cell(0,0,strtoupper($row['municipionacimiento']));
	$pdf->SetX(152);
	$pdf->Cell(0,0,strtoupper($row['departamentonacimiento']));
	$pdf->SetX(203);
	$pdf->Cell(0,0,strtoupper($row['paisnacimiento']));
	$pdf->SetY(224);
	$pdf->SetX(55);
	$fecha_nacimiento= new DateTime($row['fechanacimiento']);
	$fecha_nacimiento_parts= getdate($fecha_nacimiento->getTimestamp());
	$prt_dia_nacimiento= number2str($fecha_nacimiento_parts['mday']);
	$pdf->Cell(0,0,$prt_dia_nacimiento);
	$pdf->SetX(120);
	$pdf->Cell(0,0,strtoupper(strftime('%B',$fecha_nacimiento->getTimestamp())));
	$pdf->SetX(185);
	$pdf->Cell(0,0,number2str($fecha_nacimiento->format('Y')));
	$pdf->SetY(239);
	$pdf->SetX(63);
	$pdf->Cell(0,0,strtoupper($row['padrenombre']));
	$pdf->SetX(158);
	$pdf->Cell(0,0,strtoupper($row['nombremadre']));
	$pdf->SetY(246);
	$pdf->SetX(27);
	$fallecido_extrangero= "                                       ";
	$fallecido_extrangero.=substr($row['enextranjero'],0,220);
	$pdf->MultiCell(224,7.0,$fallecido_extrangero);
	$pdf->SetY(260);
	$pdf->SetX(25);
	$adicionales= "                            ";
	$adicionales.= $row['datosadicionales'];
	$pdf->MultiCell(224,7.0,$adicionales);
	$pdf->SetY(274);
	$pdf->SetX(25);
	$observaciones=  "                       ";
	$observaciones.= $row['observaciones'];
	$pdf->MultiCell(224,7.0,$observaciones);

	$pdf->SetY(300);
	$pdf->SetX(90);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nombre']));
	$pdf->SetY(316);
	$pdf->SetX(55);
	$pdf->Cell(0,0,$row['nombreregistrador']);
	$pdf->SetY(316);
	$pdf->SetX(190);
	$pdf->Cell(0,0,$row['nombresecretario']);

	$nac_vc=333;
	$pdf->SetY($nac_vc);
	$pdf->SetX(50);
	$pdf->Cell(0,0,$row['lugarinscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(130);
	$pdf->Cell(0,0,$row['tomoinscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(165);
	$pdf->Cell(0,0,$row['folioinscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(201);
	$pdf->Cell(0,0,$row['partidainscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(235);
	$fecha_nacimiento= new DateTime($row['fechanacimiento']);
	$pdf->Cell(0,0,$fecha_nacimiento->format('Y'));
}
$pdf->Output();
?>
