<?
header("Content-type:application/pdf");
header("Cache-Control: no-cache");
header("Pragma: no-cache");
require('/usr/share/php/fpdf/fpdf.php');
include_once('../../../common.inc.php'); 
include_once('../../../../classes/function.numeros.php'); 

$pdf=new FPDF('P','mm', array(266,346 ));
$pdf->SetAutoPageBreak(false, 10);
$pdf->AddPage();
$pdf->SetFont('Arial','',12);

$data = new inscripcionTable();
$data->readEnv();

#INSCRIPCIONES VARIAS
if ($data->request['idinscripcion']) {
        $rows = $data->readDataSQL("SELECT v.*, aj.*, ins.*, ac.idtomo, ac.folio, ac.partida, t.numero FROM inscripcionvaria v INNER JOIN actojuridico aj ON v.idinscripcionvaria=aj.idactojuridico INNER JOIN inscripcion ins ON aj.idactojuridico= ins.idinscripcion LEFT JOIN acta ac ON ac.idinscripcion=ins.idinscripcion INNER JOIN tomo t on t.idtomo=ac.idtomo WHERE ac.idinscripcion='" . $data->request['idinscripcion'] ."'");
        $row = $rows[0];
     	//$pdf->Image('./imgs/acta_inscripciones_varias.png', 34,12,230.63,329.18 );
	$pdf->SetY($ini_y + $c2_vc);
	$pdf->SetY($ini_y + $c2_vc);
	$pdf->SetY(30);
	$pdf->SetX(133);
	$pdf->Cell(0,0,strtoupper('Matagalpa'));
	$pdf->SetY(13);
        $pdf->SetX(230);
	$pdf->Cell(0,0,$row['numero']);
	$pdf->SetY(19);
        $pdf->SetX(230);
	$pdf->Cell(0,0,$row['folio']);
	$pdf->SetY(25);
        $pdf->SetX(235);
	$pdf->Cell(0,0,$row['partida']);
	$pdf->SetY(30);
        $pdf->SetX(230);
	$fecha_acta= new Datetime($row['fecha']);
	$pdf->Cell(0,0,$fecha_acta->format('d/m/Y'));
	$pdf->sety(53);
	$pdf->setx(40);
	$pdf->Cell(0,0,strtoupper($row['inscrito1nombre1']));
	$pdf->sety(53);
	$pdf->setx(95);
	$pdf->Cell(0,0,strtoupper($row['inscrito1nombre2']));
	$pdf->sety(53);
	$pdf->setx(152);
	$pdf->Cell(0,0,strtoupper($row['inscrito1apellido1']));
	$pdf->sety(53);
	$pdf->setx(212);
	$pdf->Cell(0,0,strtoupper($row['inscrito1apellido2']));
	$pdf->sety(64);
	$pdf->setx(45);
	$pdf->Cell(0,0,strtoupper($row['ciudadinscripcion']));
	$pdf->sety(64);
	$pdf->setx(175);
	$pdf->Cell(0,0,strtoupper($row['municipioinscripcion']));
        $pdf->sety(71);
	$pdf->setx(75);
	$pdf->Cell(0,0,strtoupper($row['departamentoinscripcion']));
	$pdf->sety(71);
	$pdf->setx(130);
	$fecha_inscripcion= new DateTime($row['fecha']);
	$fecha_inscripcion_parts= getdate($fecha_inscripcion->getTimestamp());
	$prt_fecha_inscripcion=number2str($fecha_inscripcion->format('g'));
	$prt_fecha_inscripcion.=" CON ". number2str($fecha_inscripcion_parts['minutes']);
	$pdf->Cell(0,0,$prt_fecha_inscripcion);
        $pdf->sety(71);
	$pdf->setx(228);
	$pdf->Cell(0,0,utf8_decode(($fecha_inscripcion_parts['hours']>12)?'TARDE':'MAÑANA'));
	$pdf->sety(77);
	$pdf->setx(55);
	$prt_dia_inscripcion= number2str($fecha_inscripcion_parts['mday']);
	$pdf->Cell(0,0,$prt_dia_inscripcion);
	$pdf->sety(77);
	$pdf->setx(130);
	$pdf->Cell(0,0,strtoupper(strftime('%B',$fecha_inscripcion->getTimestamp())));
	$pdf->sety(77);
	$pdf->setx(210);
	$pdf->Cell(0,0,number2str($fecha_inscripcion->format('y')));
	$pdf->sety(94);
	$pdf->setx(40);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nombre']));
	$pdf->sety(94);
	$pdf->setx(180);
	$pdf->Cell(0,0,number2str($row['compareciente1edad']));
	$pdf->sety(109);
	$pdf->setx(40);
	$pdf->Cell(0,0,strtoupper($row['compareciente1oficio']));
	$pdf->sety(104);
	$pdf->setx(87);
        $pdf->Cell(0,0,$row['estado_civil']);
	$pdf->sety(109);
	$pdf->setx(135);
	$pdf->SetFont('Arial','',8);
	$pdf->MultiCell(70,3.0,strtoupper($row['compareciente1domicilio']));
	//$pdf->Cell(0,0,strtoupper($row['compareciente1domicilio']));
	$pdf->SetFont('Arial','',12);
	$pdf->sety(109);
	$pdf->setx(223);
	$pdf->Cell(0,0,strtoupper($row['compareciente1cedula']));
        $pdf->sety(120);
	$pdf->setx(95);
        $pdf->Cell(0,0,strtoupper($row['tipootrainscripcion']));
	$pdf->SetY(126);
	$pdf->SetX(95);
	$pdf->Cell(0,0,strtoupper($row['jueznotario']));
	$pdf->SetY(136);
	$pdf->SetX(37);
        $partes_conducentes = $row['partesconducentes'];
	$pdf->MultiCell(225,5.5,$partes_conducentes);
	$pdf->SetY(188.5);
	$pdf->SetX(37);
	$actos_extranjero= "                                               ";
	$actos_extranjero.=$row['enextranjero'];
	$pdf->MultiCell(225,5.5,$actos_extranjero);
	$pdf->SetY(205.5);
	$pdf->SetX(37);
	$adicionales= "                              ";
	$adicionales.= $row['datosadicionales'];
	$pdf->MultiCell(225,5.5,$adicionales);
	$pdf->SetY(223.5);
	$pdf->SetX(37);
	$observaciones=  "                         ";
	$observaciones.= $row['observaciones'];
	$pdf->MultiCell(225,5.5,$observaciones);
	$pdf->SetY(252.5);
	$pdf->SetX(37);
        $modificacion_estado = '';
	$notasmarginales= $data->readDataSQL("SELECT cuerpo FROM notamarginal WHERE idinscripcion=" . $data->request['idinscripcion']." ORDER BY fechamarginacion DESC LIMIT 3");
		if(sizeof($notasmarginales)>0){
		foreach($notasmarginales as $notamarginal){
			$modificaciones[]= $notamarginal['cuerpo'];
        		$modificacion_estado .= utf8_decode($notamarginal['cuerpo']) . PHP_EOL;
		}
	}
	$mod_civil="                                                    ";
	if(sizeof(modificaciones)>0){
	$mod_civil.= $modificacion_estado;
	}
	$pdf->MultiCell(225,5.5,$mod_civil);
	$pdf->SetY(303);
	$pdf->SetX(100);
	$pdf->Cell(0,0,strtoupper($row['compareciente1nombre']));
	$pdf->SetY(315);
	$pdf->SetX(40);
	$pdf->Cell(0,0,strtoupper($row['nombreregistrador']));
	$pdf->SetY(315);
	$pdf->SetX(175);
	$pdf->Cell(0,0,strtoupper($row['nombresecretario']));
	$nac_vc= 338;
	$pdf->SetY($nac_vc);
	$pdf->SetX(65);
	$pdf->Cell(0,0,strtoupper($row['lugarinscripcionnacimiento']));
	$pdf->SetY($nac_vc);
	$pdf->SetX(163);
        $pdf->Cell(0,0,$row['tomoinscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(191);
        $pdf->Cell(0,0,$row['folioinscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(223);
        $pdf->Cell(0,0,$row['partidainscripcionnacimiento']);
	$pdf->SetY($nac_vc);
	$pdf->SetX(249);
        $pdf->Cell(0,0,$row['anyoinscripcionnacimiento']);

}
$pdf->Output();
?>
